[package]
name = "backend"
version = "0.1.0"
edition = "2021"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
async-trait = "0.1.67"
lazy_static = "1.4.0"
reqwest = { version = "0.11.14", features = ["json"] }
serde = { version = "1.0.157", features = ["derive"] }
serde_json = "1.0.94"
tokio = { version = "1.26.0", features = ["full"] }
warp = "0.3.3"
common = { path = "../common" }
profanity = { path = "../profanity" }
postcard = { version = "1.0.4", features = ["alloc"] }
flate2 = "1.0.25"
env_logger = "0.10.0"
diesel = { version = "2.0.3", features = ["chrono"]  }
diesel-async = { version = "0.2.2", features = ["postgres", "deadpool"] }
deadpool = { version = "0.9.5" }
dsync = "0.0.13"
chrono = { version = "0.4.24", features = ["serde"] }
csv = "1.2.1"
nanoid = "0.4.0"
bytes = "1.4.0"
futures = "0.3.28"
async-recursion = "1.0.4"
thumbnailer = "0.4.0"
mime = "0.3.17"
rand = "0.8.5"
web-push = "0.9.5"
imageproc = "0.23.0"
image = "0.24.6"
rusttype = "0.9.3"
async-stream = "0.3.5"
