[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
chrono = "0.4.24"
serde = { version = "1.0.159", features = ["derive"] }
sha2 = "0.10.6"
typemap = "0.3.3"